[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
title = "Alacritty"
padding = { x = 5, y = 5 }

[window.class]
general = "Alacritty"
instance = "Alacritty"
